version: '3.9'

services:
  postgres1:
    image: postgres:14.1-alpine
    restart: on-failure
    env_file: .env
    volumes:
      - ./initdb.d/shard_1.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data_1:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  postgres2:
    image: postgres:14.1-alpine
    restart: on-failure
    env_file: .env
    volumes:
      - ./initdb.d/shard_2.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data_2:/var/lib/postgresql/data

  postgres3:
    image: postgres:14.1-alpine
    restart: on-failure
    env_file: .env
    volumes:
      - ./initdb.d/shard_3.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data_3:/var/lib/postgresql/data

volumes:
  pg_data_1: { }
  pg_data_2: { }
  pg_data_3: { }
